### ISSUE TITLE
Declaring the use of the extension from the Antora CLI does not work

### ISSUE THREAD

**Issue by tl3gr4nd** [ggrossetie/asciidoctor-kroki#409]
Hello,

To build my documentation, I would like to use the Antora preloading system [1] instead of using the Antora global asciidoctor extension one [2]. That will avoid me to declare each time the extension in each Antora playbook (antora-playbook.yml).

When I execute Antora via the CLI using the `--require` argument, the diagrams are not generated in an image format but in the ditaa format:

```bash
antora --require 'asciidoctor-kroki' generate --attribute kroki-fetch-diagram=true" antora-playbook.yml
```

But, when I declare the extension in my playbook, that works even if I declare the attribute in the CLI command:

```yaml
site:
  title: My documentation
content:
  sources:
    - url: ../
      branches: HEAD
      start_path: docs/src
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
asciidoc:
   extensions:
     - asciidoctor-kroki
```

```bash
antora generate --attribute kroki-fetch-diagram=true" antora-playbook.yml
```

Do I misuse the extension or is it a bug?

[1] https://docs.antora.org/antora/latest/playbook/asciidoc-extensions/#preload-extensions
[2] https://docs.antora.org/antora/latest/playbook/asciidoc-extensions/#global-extensions
