### ISSUE TITLE
asciidoctor-kroki breaks when using remote content repositories

### ISSUE THREAD

**Issue by joostschriek** [ggrossetie/asciidoctor-kroki#416]
we have various playbooks and remote content sources setup. we've recently introduced kroki as a way to not manually copy paste diagrams from MSPaint or lucid w/e. While this all works perfectly with local content sources, having them as remote content sources results in the following error;

```
Skipping diagramsnet block macro. The "path" argument must be of type string. Received undefined
```

During our builds we install all the required npm extensions; 

```
npm i -g @antora/cli@3.0.0 @antora/site-generator@3.0.0 asciidoctor-kroki asciidoctor-external-callout
```

we call the extensions like so

```
.Context view diagram
diagramsnet::{partial-prefix}/context-view.drawio[format=png]
```

During our debugging we've figured out that local works but remote doesn't. We've tried the following remediations;

- setting the cache dir to see if we can look at the content it loads. this sadly didn't work as the only thing in the cache dir are the ui-bundle and the bare repos.
- setting the kroki attributes on the module.yaml (yes, they have always been in the playbook). this also didn't work.
- switching version. we're currently on 3.0, either down- or upgrading didn't work.
- various different incantations of the diagramsnet block.

A remote playbook
```yaml
site:
  title: SuperSecure Internal Documentation
  url: https://supersecure.acme.dope
  start_page: documentation-solution-overview::introduction-to-docs-as-code.adoc

content:
  sources:
 	.....more content sources
    - url: https://github.com/acme-dope/cloudops-docs.git
      branches: main
      start_path: documentation
   
asciidoc:
  attributes:
    kroki-server-url: https://kroki.acme.dope
    kroki-fetch-diagram: true
  extensions:
    - asciidoctor-kroki
    - asciidoctor-external-callout

	...ui bundle

```

A local playbook
```yaml
site:
  title: Cloud Operations Documentation
  url: https://supersecure.acme.dope
  start_page: cloud-operations-documentation::index.adoc
content:
  sources:
    - url: ./../../
      start_path: documentation

asciidoc:
  attributes:
    kroki-server-url: https://kroki.acme.dope
    kroki-fetch-diagram: true
  extensions:
  - asciidoctor-kroki
  - asciidoctor-external-callout

  ...ui bundle
```
